module.exports = (sequelize, DataTypes) => {
    var Billing = sequelize.define('billing', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        doctorId: {
            type: DataTypes.INTEGER //this will the doctorId for which it is created
        },
        visitorId: {
            type: DataTypes.INTEGER // this will be visitorId for which visitor it is created
        },
        consultationId: {
            type: DataTypes.INTEGER //this is the group's primary key
        },
        orderId: {
            type: DataTypes.INTEGER, //this is the orderID generated by us for tracking the payment
        },
        trackingId: {  
            type: DataTypes.INTEGER, //this is the trackingId generated by ccavenue for tracking the payment status
        },
        failureMessage: {  
            type: DataTypes.STRING, //this is the failure message generated by ccavenue for payment failure
        },
        cardName: {  
            type: DataTypes.STRING, //this is the cardName from which payment is done in case payment is successfull
        },
        status: {
            type: DataTypes.STRING //due, Success, Aborted, Failure
        },
        amount: {
            type: DataTypes.INTEGER, //consultation charges, taxes((cgst, sgst(inside Karnataka)), igst(outside Karnataka))
        },
        date: {
            type: DataTypes.DATE //date on which the bill generated
        },
        speciality: {
            type: DataTypes.STRING,
        },
        consultationMode: {
            type: DataTypes.STRING, //doctors speciality chosen
        },
        location: {
            type: DataTypes.STRING, //doctors speciality chosen
        },
        description: {
            type: DataTypes.STRING //regarding billing details
        },
        referenceNumber: {
            type: DataTypes.STRING //after payment done, it is generated
        },
        modeOfPayment: {
            type: DataTypes.STRING //free credits, net banking, payment gateways etc.
        },
        url: {
            type: DataTypes.STRING //filename of the billing pdf
        },
        createdBy: {
            type: DataTypes.INTEGER,
            defaultValue: null
        },
        updatedBy: {
            type: DataTypes.INTEGER,
            defaultValue: null
        }
    }, {
        freezeTableName: true
    });
    return Billing;
};